### ISSUE TITLE
R44 - Enviar mensaje privado a otro usuario

### ISSUE THREAD

**Issue by carlosgarcia8** [carlosgarcia8/gkri#78]
El usuario podrá tener la opción en el perfil de otro usuario de
mandarle un mensaje privado.

**Comment by GATMgarrett** [comment]
Hola como estan?

**Comment by RobStackit** [comment]
Como mando mensajes a otros usuarios?

**Comment by crlsoe** [comment]
Solo quiero saber como mandar mensaje a otros usr ya que debo mandarle urgentemente a un usr mensaje por favor 
:c es mi ex, quiero decirle que le van  a mandar un virus  en apk en una url falsa :c

**Comment by crlsoe** [comment]
Ivonne si lees esto Te extraño solo quiero estar contigo una ultima vez contigo y no hay mujer que pueda amar mas que a ti :(  Te amo.. </3

**Comment by intercoursewithyourmom** [comment]
Chingadamadre yo no entiendo nada de código solamente quiero contactar a un amigo mío que ya no se conecta en ig y whatsapp desde hace meses y lo extraño :(

**Comment by jhonjrod** [comment]
> Chingadamadre yo no entiendo nada de código solamente quiero contactar a un amigo mío que ya no se conecta en ig y whatsapp desde hace meses y lo extraño :(

Pudiste?
